Week2
Lidemy/mentor-program-5th-torai55 pull request #3
Opened 2021-04-25 09:00 UTC by torai55

第二週作業完成

2021-04-25 12:44 UTC, cwc329 reviewed
有解挑戰題 GJ。
不過可以注意繳交作業的時候不要把不必要的程式碼一併提交。
像是不必要的 function call 與 console.log。
還有 hw2 與 hw6 未達標準，請訂正之後再次上傳。
訂正完之後可以 tag 我，我會再來看。

2021-04-25 12:44 UTC, cwc329 commented on homeworks/week2/challenge.js
> +console.log(search([1, 3, 10, 14, 39], 0));
GJ!

2021-04-25 12:44 UTC, cwc329 commented on homeworks/week2/hw2.js
這題不對喔。

2021-04-25 12:44 UTC, cwc329 commented on homeworks/week2/hw6.md
> +4. i=0，`arr[i] <= 0` 回傳 false，不進入 if 執行區塊， i++。
i = 0 為何會進入迴圈？

2021-04-25 12:44 UTC, cwc329 commented on homeworks/week2/hw6.md
> +4. i=0，`arr[i] <= 0` 回傳 false，不進入 if 執行區塊， i++。
`arr[i] <= 0` 不是函式，應該不會回傳值。
又，`arr[i]` 的值又是多少？

2021-04-25 12:44 UTC, cwc329 commented on homeworks/week2/supersuperChallenge.js
> +      if (result[aIndex + bIndex + 1] == null) {
我個人不太建議用 `==`，可以想其他方式來判斷。

2021-04-25 12:44 UTC, cwc329 commented on homeworks/week2/supersuperChallenge.js
> +      console.log(result);
這是不相干的 `console.log`，建議移除。

2021-04-25 12:46 UTC, cwc329 requested changes
訂正完之後可以 tag 我，我會再來看。

2021-04-26 04:36 UTC, torai55 commented on homeworks/week2/hw2.js
改成直接用內建函式，toUpperCase 轉大寫的方法。

2021-04-26 04:38 UTC, torai55 commented on homeworks/week2/hw6.md
> +4. i=0，`arr[i] <= 0` 回傳 false，不進入 if 執行區塊， i++。
應該說進入迴圈後， 才指定 i=0

2021-04-26 04:43 UTC, torai55 commented on homeworks/week2/hw6.md
> +4. i=0，`arr[i] <= 0` 回傳 false，不進入 if 執行區塊， i++。
原本是想說 `if(expression){}` 中間 expression 的部分是表達式，在執行完之後會回傳 true 或 false 以供 if statement 判斷後決定要不要執行尖括號裡面的區塊。
可能跟函式的 return 混淆了，改個用詞。
`arr[i]` 的值已補上。

2021-04-26 04:48 UTC, torai55 commented on homeworks/week2/supersuperChallenge.js
> +      if (result[aIndex + bIndex + 1] == null) {
這邊不應該用 `null`，因為宣告之後沒有指定初始值，在 JavaScript 中會回傳 `undefined`，所以應該改成判斷是否為 undefined。
上網查了之後，有看到一些用法：
* `typeof(x) === 'undefined`
* `x === undefined`
不過放在 if 裡面改成 `!result[aIndex + bIndex +1]` 更簡便。
不曉得助教指的是不是這個？

2021-04-26 04:50 UTC, torai55 commented
@cwc329 移除不必要的 `console.log` 及 hw2、hw 6 修改。再麻煩助教批改，感謝。

2021-04-28 12:28 UTC, cwc329 commented on homeworks/week2/supersuperChallenge.js
> +      if (result[aIndex + bIndex + 1] == null) {
我自己通常會用 `x === undefined` 或者偷懶一點會 `!x`。
會這樣建議是因為 `==` 有太多其他因素要考慮，因為它會自動做型態轉換。
同理其實 `!x` 也不算是很好的方法，因為 `0` 也是 falsy，如果需要用到 `0` 就會變得比較麻煩。
所以我會建議可以的話不要去用 `==`。

2021-04-28 12:31 UTC, cwc329 commented on homeworks/week2/supersuperChallenge.js
> +}
GJ!

2021-04-28 12:31 UTC, cwc329 commented on homeworks/week2/hw6.md
> +4. i=0，`i < arr.length` 成立，繼續執行迴圈，arr[i]=3；`arr[i] <= 0` 不成立，不進入 if 執行區塊，i++。
arr.length 的值是什麼？

2021-04-28 12:31 UTC, cwc329 commented on homeworks/week2/hw6.md
> +12. i=2，`i < arr.length` 成立，繼續執行迴圈；`arr[i] !== arr[i - 1] + arr[i - 2]` 不成立，不進入 if 執行區塊，i++。
`arr[i]`, `arr[i - 1]`, `arr[i - 2]` 的值又各是什麼？

2021-04-28 12:33 UTC, cwc329 commented
有訂正給推！
挑戰題有完成也給推！

不過 hw6 建議寫得更詳細一些，
寫得越詳細助教們越能知道你了解到多深。

2021-04-29 19:09 UTC, merged

2021-05-01 13:02 UTC, torai55 commented on homeworks/week2/hw6.md
> +4. i=0，`i < arr.length` 成立，繼續執行迴圈，arr[i]=3；`arr[i] <= 0` 不成立，不進入 if 執行區塊，i++。
arr.length 的值為 6，在進入函式之後就沒有再改變。想說省略不寫看起來比較不亂。

2021-05-01 13:05 UTC, torai55 commented on homeworks/week2/hw6.md
> +12. i=2，`i < arr.length` 成立，繼續執行迴圈；`arr[i] !== arr[i - 1] + arr[i - 2]` 不成立，不進入 if 執行區塊，i++。
這邊也因為 `arr` 這個變數不變，帶入 `i` 的值就能直接看到結果。例如 `i=2` 時， `arr[i]=8, arr[i-1]=5, arr[i-2]=3`，每跑一次迴圈都列出來好像感覺挺冗的。

2021-05-01 14:06 UTC, cwc329 commented on homeworks/week2/hw6.md
> +12. i=2，`i < arr.length` 成立，繼續執行迴圈；`arr[i] !== arr[i - 1] + arr[i - 2]` 不成立，不進入 if 執行區塊，i++。
關於 arr 不變，
迴圈能保證這件事情嗎？
這是電腦能保證的事情嗎？
還是這是你在模擬之後才發現的？

這個作業是要模擬電腦怎麼做，
而在我的認知裡，電腦並不會這樣做，
電腦會很冗地在每一次讀到 arr.length、arr[i] 才去看值是多少。